name: CMake

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup
      uses: ilammy/msvc-dev-cmd@v1.12.0
      with:
        arch: x86

    - name: Cache bin
      id: cache-bin
      uses: actions/cache@v3
      with:
        path: bin
        key: ${{ runner.os }}-bin

    - name: Create bin folder
      if: steps.cache-bin.outputs.cache-hit != 'true'
      run: |
        mkdir bin
        cd bin
        cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release ../
        mkdir output_SA
    
    - name: Compile
      run: |
        cd bin
        ninja
        cp TrilogyChaosMod.SA.asi output_SA/TrilogyChaosMod.SA.asi

    - name: Upload SA
      uses: actions/upload-artifact@v1
      with:
        name: "TrilogyChaosMod.SA"
        path: bin/output_SA
        
    - name: Move ASI for Upload
      run: |
        mv bin/output_SA/TrilogyChaosMod.SA.asi .
        
    - name: Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'release.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig cmake lib src test CMakeLists.txt README.md CONTRIBUTING.md .gitignore .clang-format'
