name: CMake

on: 
  push:
    tags:
      - "**"
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4

    - name: Setup
      uses: ilammy/msvc-dev-cmd@v1.13.0
      with:
        arch: x86

    - name: Cache bin
      id: cache-bin
      uses: actions/cache@v4
      with:
        path: bin
        key: ${{ runner.os }}-bin

    - name: Create bin folder
      if: steps.cache-bin.outputs.cache-hit != 'true'
      run: |
        mkdir bin
        cd bin
        cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release ../
        mkdir output_SA
    
    - name: Compile
      run: |
        cd bin
        ninja
        cp TrilogyChaosMod.SA.asi output_SA/TrilogyChaosMod.SA.asi

    - name: Upload SA
      uses: actions/upload-artifact@v4
      with:
        name: "TrilogyChaosMod.SA"
        path: bin/output_SA
        
    - name: Zip
      uses: vimtor/action-zip@v1.2
      with:
        files: bin/output_SA resources/
        dest: SA-CHAOS.zip

    - uses: actions/setup-node@v3

    - uses: seepine/hash-files@v1
      id: get-hash
      with: 
        patterns: "*.asi"
    
    - name: Echo hash
      run: echo ${{ steps.get-hash.outputs.hash }}
    
    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        allowUpdates: "true"
        omitBody: true
        artifacts: "SA-CHAOS.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
