name: Test Build

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Clone GuillaumeFalourd/poc-github-actions PUBLIC repository
        uses: GuillaumeFalourd/clone-github-repo-action@v2.3
        with:
          depth: 1
          branch: 'king'
          owner: 'AthallahDzaki'
          repository: 'SA-Chaos-Hash'
          access-token: ${{ secrets.API_TOKEN_GITHUB }}
    
      - name: Do Push
        run: |
          git config --global user.email "athallahdzaki@gmail.com"
          git config --global user.name "AthallahDzaki"
          FOR /F "tokens=2 USEBACKQ" %%F IN (`openssl dgst -sha256 *.asi`) DO echo %%F > SA-Chaos-Hash/chaosmod.hash
          cd SA-Chaos-Hash
          git add .
          git commit -m "Update Hash"
          git push
          cd ../
          
      
